DATA_PATHS:
  RAW_DATA:
    2_CLASS_RAW_DATA: "data/raw/2_class_resnet/"
    7_CLASS_RAW_DATA: "data/raw/updated_ds/"

  FSL_DATA:
    6_CLASS_FSL_DATA: "data/processed/fsl_data_7/"
    10_CLASS_FSL_DATA: "data/processed/updated_data_fsl/"

DATA:
  DATA_MEAN: [0.4609, 0.4467, 0.4413]
  DATA_STD: [0.1314, 0.1239, 0.1198]
  
DATA_CLASSES:
  2_CLASS: ['buoys', 'ships']
  6_CLASS: ['buoys', 'human', 'large_commercial_vessel', 'leisure_craft', 'sailboats', 'small_medium_fishing_boat']
  7_CLASS: ['buoys', 'harbour', 'human', 'large_commercial_vessel', 'leisure_craft', 'sailboats', 'small_medium_fishing_boat']
  10_CLASS: ['Sailboat_D', 'Sailboat_U', 'buoy_green', 'buoy_random', 'buoy_red', 'harbour', 'human', 'large_commercial_vessel', 'leisure_craft', 'small_medium_fishing_boat']
  


TEST_CONFIG:
  n_shot: 10